/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';
import Body from './model/Body';
import CookbookAddRequest from './model/CookbookAddRequest';
import CookbookResponse from './model/CookbookResponse';
import CookbookUpdateRequest from './model/CookbookUpdateRequest';
import CookbookWithGroupResponse from './model/CookbookWithGroupResponse';
import GroupAddRequest from './model/GroupAddRequest';
import GroupJoinedResponse from './model/GroupJoinedResponse';
import GroupPublicResponse from './model/GroupPublicResponse';
import GroupUpdateRequest from './model/GroupUpdateRequest';
import GroupUserAdminResponse from './model/GroupUserAdminResponse';
import GroupUserResponse from './model/GroupUserResponse';
import GroupUserUpdateRequest from './model/GroupUserUpdateRequest';
import InlineResponse400 from './model/InlineResponse400';
import LoginRequest from './model/LoginRequest';
import OneOfinlineResponse400 from './model/OneOfinlineResponse400';
import RecipeAddHardwareRequest from './model/RecipeAddHardwareRequest';
import RecipeAddIngredientCategoryRequest from './model/RecipeAddIngredientCategoryRequest';
import RecipeAddIngredientRequest from './model/RecipeAddIngredientRequest';
import RecipeAddLabelRequest from './model/RecipeAddLabelRequest';
import RecipeAddRequest from './model/RecipeAddRequest';
import RecipeAddStepRequest from './model/RecipeAddStepRequest';
import RecipeHardwareResponse from './model/RecipeHardwareResponse';
import RecipeIngredientCategoryResponse from './model/RecipeIngredientCategoryResponse';
import RecipeIngredientResponse from './model/RecipeIngredientResponse';
import RecipeLabelResponse from './model/RecipeLabelResponse';
import RecipeListResponse from './model/RecipeListResponse';
import RecipeResponse from './model/RecipeResponse';
import RecipeStepResponse from './model/RecipeStepResponse';
import RecipeUpdateHardwareRequest from './model/RecipeUpdateHardwareRequest';
import RecipeUpdateIngredientCategoryRequest from './model/RecipeUpdateIngredientCategoryRequest';
import RecipeUpdateIngredientRequest from './model/RecipeUpdateIngredientRequest';
import RecipeUpdateLabelRequest from './model/RecipeUpdateLabelRequest';
import RecipeUpdateRequest from './model/RecipeUpdateRequest';
import RecipeUpdateStepRequest from './model/RecipeUpdateStepRequest';
import SecurityConfiguration from './model/SecurityConfiguration';
import SwaggerResource from './model/SwaggerResource';
import UiConfiguration from './model/UiConfiguration';
import UserRegisterRequest from './model/UserRegisterRequest';
import UserResponse from './model/UserResponse';
import UserUpdateRequest from './model/UserUpdateRequest';
import ApiResourceControllerApi from './api/ApiResourceControllerApi';
import CookbookControllerApi from './api/CookbookControllerApi';
import GroupControllerApi from './api/GroupControllerApi';
import RecipeControllerApi from './api/RecipeControllerApi';
import UserControllerApi from './api/UserControllerApi';

/**
* Object.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OpenApiDefinition = require('index'); // See note below*.
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Body model constructor.
     * @property {module:model/Body}
     */
    Body,

    /**
     * The CookbookAddRequest model constructor.
     * @property {module:model/CookbookAddRequest}
     */
    CookbookAddRequest,

    /**
     * The CookbookResponse model constructor.
     * @property {module:model/CookbookResponse}
     */
    CookbookResponse,

    /**
     * The CookbookUpdateRequest model constructor.
     * @property {module:model/CookbookUpdateRequest}
     */
    CookbookUpdateRequest,

    /**
     * The CookbookWithGroupResponse model constructor.
     * @property {module:model/CookbookWithGroupResponse}
     */
    CookbookWithGroupResponse,

    /**
     * The GroupAddRequest model constructor.
     * @property {module:model/GroupAddRequest}
     */
    GroupAddRequest,

    /**
     * The GroupJoinedResponse model constructor.
     * @property {module:model/GroupJoinedResponse}
     */
    GroupJoinedResponse,

    /**
     * The GroupPublicResponse model constructor.
     * @property {module:model/GroupPublicResponse}
     */
    GroupPublicResponse,

    /**
     * The GroupUpdateRequest model constructor.
     * @property {module:model/GroupUpdateRequest}
     */
    GroupUpdateRequest,

    /**
     * The GroupUserAdminResponse model constructor.
     * @property {module:model/GroupUserAdminResponse}
     */
    GroupUserAdminResponse,

    /**
     * The GroupUserResponse model constructor.
     * @property {module:model/GroupUserResponse}
     */
    GroupUserResponse,

    /**
     * The GroupUserUpdateRequest model constructor.
     * @property {module:model/GroupUserUpdateRequest}
     */
    GroupUserUpdateRequest,

    /**
     * The InlineResponse400 model constructor.
     * @property {module:model/InlineResponse400}
     */
    InlineResponse400,

    /**
     * The LoginRequest model constructor.
     * @property {module:model/LoginRequest}
     */
    LoginRequest,

    /**
     * The OneOfinlineResponse400 model constructor.
     * @property {module:model/OneOfinlineResponse400}
     */
    OneOfinlineResponse400,

    /**
     * The RecipeAddHardwareRequest model constructor.
     * @property {module:model/RecipeAddHardwareRequest}
     */
    RecipeAddHardwareRequest,

    /**
     * The RecipeAddIngredientCategoryRequest model constructor.
     * @property {module:model/RecipeAddIngredientCategoryRequest}
     */
    RecipeAddIngredientCategoryRequest,

    /**
     * The RecipeAddIngredientRequest model constructor.
     * @property {module:model/RecipeAddIngredientRequest}
     */
    RecipeAddIngredientRequest,

    /**
     * The RecipeAddLabelRequest model constructor.
     * @property {module:model/RecipeAddLabelRequest}
     */
    RecipeAddLabelRequest,

    /**
     * The RecipeAddRequest model constructor.
     * @property {module:model/RecipeAddRequest}
     */
    RecipeAddRequest,

    /**
     * The RecipeAddStepRequest model constructor.
     * @property {module:model/RecipeAddStepRequest}
     */
    RecipeAddStepRequest,

    /**
     * The RecipeHardwareResponse model constructor.
     * @property {module:model/RecipeHardwareResponse}
     */
    RecipeHardwareResponse,

    /**
     * The RecipeIngredientCategoryResponse model constructor.
     * @property {module:model/RecipeIngredientCategoryResponse}
     */
    RecipeIngredientCategoryResponse,

    /**
     * The RecipeIngredientResponse model constructor.
     * @property {module:model/RecipeIngredientResponse}
     */
    RecipeIngredientResponse,

    /**
     * The RecipeLabelResponse model constructor.
     * @property {module:model/RecipeLabelResponse}
     */
    RecipeLabelResponse,

    /**
     * The RecipeListResponse model constructor.
     * @property {module:model/RecipeListResponse}
     */
    RecipeListResponse,

    /**
     * The RecipeResponse model constructor.
     * @property {module:model/RecipeResponse}
     */
    RecipeResponse,

    /**
     * The RecipeStepResponse model constructor.
     * @property {module:model/RecipeStepResponse}
     */
    RecipeStepResponse,

    /**
     * The RecipeUpdateHardwareRequest model constructor.
     * @property {module:model/RecipeUpdateHardwareRequest}
     */
    RecipeUpdateHardwareRequest,

    /**
     * The RecipeUpdateIngredientCategoryRequest model constructor.
     * @property {module:model/RecipeUpdateIngredientCategoryRequest}
     */
    RecipeUpdateIngredientCategoryRequest,

    /**
     * The RecipeUpdateIngredientRequest model constructor.
     * @property {module:model/RecipeUpdateIngredientRequest}
     */
    RecipeUpdateIngredientRequest,

    /**
     * The RecipeUpdateLabelRequest model constructor.
     * @property {module:model/RecipeUpdateLabelRequest}
     */
    RecipeUpdateLabelRequest,

    /**
     * The RecipeUpdateRequest model constructor.
     * @property {module:model/RecipeUpdateRequest}
     */
    RecipeUpdateRequest,

    /**
     * The RecipeUpdateStepRequest model constructor.
     * @property {module:model/RecipeUpdateStepRequest}
     */
    RecipeUpdateStepRequest,

    /**
     * The SecurityConfiguration model constructor.
     * @property {module:model/SecurityConfiguration}
     */
    SecurityConfiguration,

    /**
     * The SwaggerResource model constructor.
     * @property {module:model/SwaggerResource}
     */
    SwaggerResource,

    /**
     * The UiConfiguration model constructor.
     * @property {module:model/UiConfiguration}
     */
    UiConfiguration,

    /**
     * The UserRegisterRequest model constructor.
     * @property {module:model/UserRegisterRequest}
     */
    UserRegisterRequest,

    /**
     * The UserResponse model constructor.
     * @property {module:model/UserResponse}
     */
    UserResponse,

    /**
     * The UserUpdateRequest model constructor.
     * @property {module:model/UserUpdateRequest}
     */
    UserUpdateRequest,

    /**
    * The ApiResourceControllerApi service constructor.
    * @property {module:api/ApiResourceControllerApi}
    */
    ApiResourceControllerApi,

    /**
    * The CookbookControllerApi service constructor.
    * @property {module:api/CookbookControllerApi}
    */
    CookbookControllerApi,

    /**
    * The GroupControllerApi service constructor.
    * @property {module:api/GroupControllerApi}
    */
    GroupControllerApi,

    /**
    * The RecipeControllerApi service constructor.
    * @property {module:api/RecipeControllerApi}
    */
    RecipeControllerApi,

    /**
    * The UserControllerApi service constructor.
    * @property {module:api/UserControllerApi}
    */
    UserControllerApi
};
