/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse400 model module.
* @module model/InlineResponse400
* @version v0
*/
export default class InlineResponse400 {
    /**
    * Constructs a new <code>InlineResponse400</code>.
    * @alias module:model/InlineResponse400
    * @class
    */

    constructor() {
        
        OneOfinlineResponse400.call(this);
        
    }

    /**
    * Constructs a <code>InlineResponse400</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse400} obj Optional instance to populate.
    * @return {module:model/InlineResponse400} The populated <code>InlineResponse400</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse400();
                        
            
        }
        return obj;
    }


    // Implement OneOfinlineResponse400 interface:
    


}
