/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RecipeAddIngredientRequest from './RecipeAddIngredientRequest';

/**
* The RecipeAddIngredientCategoryRequest model module.
* @module model/RecipeAddIngredientCategoryRequest
* @version v0
*/
export default class RecipeAddIngredientCategoryRequest {
    /**
    * Constructs a new <code>RecipeAddIngredientCategoryRequest</code>.
    * @alias module:model/RecipeAddIngredientCategoryRequest
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>RecipeAddIngredientCategoryRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RecipeAddIngredientCategoryRequest} obj Optional instance to populate.
    * @return {module:model/RecipeAddIngredientCategoryRequest} The populated <code>RecipeAddIngredientCategoryRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RecipeAddIngredientCategoryRequest();
                        
            
            if (data.hasOwnProperty('sequenceNumber')) {
                obj['sequenceNumber'] = ApiClient.convertToType(data['sequenceNumber'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('ingredientList')) {
                obj['ingredientList'] = ApiClient.convertToType(data['ingredientList'], [RecipeAddIngredientRequest]);
            }
        }
        return obj;
    }

    /**
    * @member {Number} sequenceNumber
    */
    sequenceNumber = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {Array.<module:model/RecipeAddIngredientRequest>} ingredientList
    */
    ingredientList = undefined;




}
