/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The SecurityConfiguration model module.
* @module model/SecurityConfiguration
* @version v0
*/
export default class SecurityConfiguration {
    /**
    * Constructs a new <code>SecurityConfiguration</code>.
    * @alias module:model/SecurityConfiguration
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>SecurityConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SecurityConfiguration} obj Optional instance to populate.
    * @return {module:model/SecurityConfiguration} The populated <code>SecurityConfiguration</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SecurityConfiguration();
                        
            
            if (data.hasOwnProperty('apiKey')) {
                obj['apiKey'] = ApiClient.convertToType(data['apiKey'], 'String');
            }
            if (data.hasOwnProperty('apiKeyVehicle')) {
                obj['apiKeyVehicle'] = ApiClient.convertToType(data['apiKeyVehicle'], 'String');
            }
            if (data.hasOwnProperty('apiKeyName')) {
                obj['apiKeyName'] = ApiClient.convertToType(data['apiKeyName'], 'String');
            }
            if (data.hasOwnProperty('clientId')) {
                obj['clientId'] = ApiClient.convertToType(data['clientId'], 'String');
            }
            if (data.hasOwnProperty('clientSecret')) {
                obj['clientSecret'] = ApiClient.convertToType(data['clientSecret'], 'String');
            }
            if (data.hasOwnProperty('realm')) {
                obj['realm'] = ApiClient.convertToType(data['realm'], 'String');
            }
            if (data.hasOwnProperty('appName')) {
                obj['appName'] = ApiClient.convertToType(data['appName'], 'String');
            }
            if (data.hasOwnProperty('scopeSeparator')) {
                obj['scopeSeparator'] = ApiClient.convertToType(data['scopeSeparator'], 'String');
            }
            if (data.hasOwnProperty('additionalQueryStringParams')) {
                obj['additionalQueryStringParams'] = ApiClient.convertToType(data['additionalQueryStringParams'], {'String': Object});
            }
            if (data.hasOwnProperty('useBasicAuthenticationWithAccessCodeGrant')) {
                obj['useBasicAuthenticationWithAccessCodeGrant'] = ApiClient.convertToType(data['useBasicAuthenticationWithAccessCodeGrant'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * @member {String} apiKey
    */
    apiKey = undefined;
    /**
    * @member {String} apiKeyVehicle
    */
    apiKeyVehicle = undefined;
    /**
    * @member {String} apiKeyName
    */
    apiKeyName = undefined;
    /**
    * @member {String} clientId
    */
    clientId = undefined;
    /**
    * @member {String} clientSecret
    */
    clientSecret = undefined;
    /**
    * @member {String} realm
    */
    realm = undefined;
    /**
    * @member {String} appName
    */
    appName = undefined;
    /**
    * @member {String} scopeSeparator
    */
    scopeSeparator = undefined;
    /**
    * @member {Object.<String, Object>} additionalQueryStringParams
    */
    additionalQueryStringParams = undefined;
    /**
    * @member {Boolean} useBasicAuthenticationWithAccessCodeGrant
    */
    useBasicAuthenticationWithAccessCodeGrant = undefined;




}
