/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The SwaggerResource model module.
* @module model/SwaggerResource
* @version v0
*/
export default class SwaggerResource {
    /**
    * Constructs a new <code>SwaggerResource</code>.
    * @alias module:model/SwaggerResource
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>SwaggerResource</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SwaggerResource} obj Optional instance to populate.
    * @return {module:model/SwaggerResource} The populated <code>SwaggerResource</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SwaggerResource();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('swaggerVersion')) {
                obj['swaggerVersion'] = ApiClient.convertToType(data['swaggerVersion'], 'String');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = ApiClient.convertToType(data['location'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} url
    */
    url = undefined;
    /**
    * @member {String} swaggerVersion
    */
    swaggerVersion = undefined;
    /**
    * @member {String} location
    */
    location = undefined;




}
