/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The UiConfiguration model module.
* @module model/UiConfiguration
* @version v0
*/
export default class UiConfiguration {
    /**
    * Constructs a new <code>UiConfiguration</code>.
    * @alias module:model/UiConfiguration
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UiConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UiConfiguration} obj Optional instance to populate.
    * @return {module:model/UiConfiguration} The populated <code>UiConfiguration</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UiConfiguration();
                        
            
            if (data.hasOwnProperty('deepLinking')) {
                obj['deepLinking'] = ApiClient.convertToType(data['deepLinking'], 'Boolean');
            }
            if (data.hasOwnProperty('displayOperationId')) {
                obj['displayOperationId'] = ApiClient.convertToType(data['displayOperationId'], 'Boolean');
            }
            if (data.hasOwnProperty('defaultModelsExpandDepth')) {
                obj['defaultModelsExpandDepth'] = ApiClient.convertToType(data['defaultModelsExpandDepth'], 'Number');
            }
            if (data.hasOwnProperty('defaultModelExpandDepth')) {
                obj['defaultModelExpandDepth'] = ApiClient.convertToType(data['defaultModelExpandDepth'], 'Number');
            }
            if (data.hasOwnProperty('defaultModelRendering')) {
                obj['defaultModelRendering'] = ApiClient.convertToType(data['defaultModelRendering'], 'String');
            }
            if (data.hasOwnProperty('displayRequestDuration')) {
                obj['displayRequestDuration'] = ApiClient.convertToType(data['displayRequestDuration'], 'Boolean');
            }
            if (data.hasOwnProperty('docExpansion')) {
                obj['docExpansion'] = ApiClient.convertToType(data['docExpansion'], 'String');
            }
            if (data.hasOwnProperty('filter')) {
                obj['filter'] = ApiClient.convertToType(data['filter'], Object);
            }
            if (data.hasOwnProperty('maxDisplayedTags')) {
                obj['maxDisplayedTags'] = ApiClient.convertToType(data['maxDisplayedTags'], 'Number');
            }
            if (data.hasOwnProperty('operationsSorter')) {
                obj['operationsSorter'] = ApiClient.convertToType(data['operationsSorter'], 'String');
            }
            if (data.hasOwnProperty('showExtensions')) {
                obj['showExtensions'] = ApiClient.convertToType(data['showExtensions'], 'Boolean');
            }
            if (data.hasOwnProperty('tagsSorter')) {
                obj['tagsSorter'] = ApiClient.convertToType(data['tagsSorter'], 'String');
            }
            if (data.hasOwnProperty('validatorUrl')) {
                obj['validatorUrl'] = ApiClient.convertToType(data['validatorUrl'], 'String');
            }
            if (data.hasOwnProperty('apisSorter')) {
                obj['apisSorter'] = ApiClient.convertToType(data['apisSorter'], 'String');
            }
            if (data.hasOwnProperty('jsonEditor')) {
                obj['jsonEditor'] = ApiClient.convertToType(data['jsonEditor'], 'Boolean');
            }
            if (data.hasOwnProperty('showRequestHeaders')) {
                obj['showRequestHeaders'] = ApiClient.convertToType(data['showRequestHeaders'], 'Boolean');
            }
            if (data.hasOwnProperty('supportedSubmitMethods')) {
                obj['supportedSubmitMethods'] = ApiClient.convertToType(data['supportedSubmitMethods'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {Boolean} deepLinking
    */
    deepLinking = undefined;
    /**
    * @member {Boolean} displayOperationId
    */
    displayOperationId = undefined;
    /**
    * @member {Number} defaultModelsExpandDepth
    */
    defaultModelsExpandDepth = undefined;
    /**
    * @member {Number} defaultModelExpandDepth
    */
    defaultModelExpandDepth = undefined;
    /**
    * @member {module:model/UiConfiguration.DefaultModelRenderingEnum} defaultModelRendering
    */
    defaultModelRendering = undefined;
    /**
    * @member {Boolean} displayRequestDuration
    */
    displayRequestDuration = undefined;
    /**
    * @member {module:model/UiConfiguration.DocExpansionEnum} docExpansion
    */
    docExpansion = undefined;
    /**
    * @member {Object} filter
    */
    filter = undefined;
    /**
    * @member {Number} maxDisplayedTags
    */
    maxDisplayedTags = undefined;
    /**
    * @member {module:model/UiConfiguration.OperationsSorterEnum} operationsSorter
    */
    operationsSorter = undefined;
    /**
    * @member {Boolean} showExtensions
    */
    showExtensions = undefined;
    /**
    * @member {module:model/UiConfiguration.TagsSorterEnum} tagsSorter
    */
    tagsSorter = undefined;
    /**
    * @member {String} validatorUrl
    */
    validatorUrl = undefined;
    /**
    * @member {String} apisSorter
    */
    apisSorter = undefined;
    /**
    * @member {Boolean} jsonEditor
    */
    jsonEditor = undefined;
    /**
    * @member {Boolean} showRequestHeaders
    */
    showRequestHeaders = undefined;
    /**
    * @member {Array.<String>} supportedSubmitMethods
    */
    supportedSubmitMethods = undefined;



    /**
    * Allowed values for the <code>defaultModelRendering</code> property.
    * @enum {String}
    * @readonly
    */
    static DefaultModelRenderingEnum = {
        /**
         * value: "EXAMPLE"
         * @const
         */
        "EXAMPLE": "EXAMPLE",
        /**
         * value: "MODEL"
         * @const
         */
        "MODEL": "MODEL"    };
    /**
    * Allowed values for the <code>docExpansion</code> property.
    * @enum {String}
    * @readonly
    */
    static DocExpansionEnum = {
        /**
         * value: "NONE"
         * @const
         */
        "NONE": "NONE",
        /**
         * value: "LIST"
         * @const
         */
        "LIST": "LIST",
        /**
         * value: "FULL"
         * @const
         */
        "FULL": "FULL"    };
    /**
    * Allowed values for the <code>operationsSorter</code> property.
    * @enum {String}
    * @readonly
    */
    static OperationsSorterEnum = {
        /**
         * value: "ALPHA"
         * @const
         */
        "ALPHA": "ALPHA",
        /**
         * value: "METHOD"
         * @const
         */
        "METHOD": "METHOD"    };
    /**
    * Allowed values for the <code>tagsSorter</code> property.
    * @enum {String}
    * @readonly
    */
    static TagsSorterEnum = {
        /**
         * value: "ALPHA"
         * @const
         */
        "ALPHA": "ALPHA"    };

}
