/**
 * Grandmas Kitchen API
 * An API for a recipe sharing website
 *
 * OpenAPI spec version: v1.0.0
 * Contact: William.G.Parish@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RecipeAddStepRequest model module.
 * @module model/RecipeAddStepRequest
 * @version v1.0.0
 */
export default class RecipeAddStepRequest {
    /**
     * Constructs a new <code>RecipeAddStepRequest</code>.
     * @alias module:model/RecipeAddStepRequest
     * @class
     */

    constructor() {


    }

    /**
     * Constructs a <code>RecipeAddStepRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RecipeAddStepRequest} obj Optional instance to populate.
     * @return {module:model/RecipeAddStepRequest} The populated <code>RecipeAddStepRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RecipeAddStepRequest();


            if (data.hasOwnProperty('sequenceNumber')) {
                obj['sequenceNumber'] = ApiClient.convertToType(data['sequenceNumber'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
        }
        return obj;
    }

    /**
     * @member {Number} sequenceNumber
     */
    sequenceNumber = undefined;
    /**
     * @member {String} description
     */
    description = undefined;
    /**
     * @member {String} title
     */
    title = undefined;


}
